print('========== DESAFIO 006 ==========')
num = int(input('Digite um número: '))
print('Dobro de {}: {}'.format(num, num*2))
print('Triplo de {}: {}'.format(num, num*3))
print('Raiz quadrada de {}: {}'.format(num, num**(1/2)))